version: '3.5'

services:
        gitlab-runner:
                image: gitlab/gitlab-runner:alpine
                restart: unless-stopped
                volumes:
                        - ./config/gitlab-runner:/etc/gitlab-runner
                        - /var/run/docker.sock:/var/run/docker.sock

